import { NextIntlClientProvider, useMessages } from "next-intl";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { NextAuthProviders } from "./Providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages()
  return (
    <html lang={locale}>
      <NextAuthProviders>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <body className={inter.className}>{children}</body>
        </NextIntlClientProvider>
        <Toaster />
      </NextAuthProviders>
    </html>
  );
}
